name: "Destroy"

on: workflow_dispatch
jobs:
  terraform:
    name: "Destroying Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployments
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform destroy
        id: destroy
        run: |
          terraform destroy

      